name: ci

concurrency: ci-${{ github.ref }}

on:
  pull_request:
  push:
  schedule:
    - cron:  '0 1 * * *'

env:
  BUNDLE_RETRY: 6
  BUNDLE_JOBS: 4

jobs:
  diffend:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Install Diffend plugin
        run: bundle plugin install diffend

      - name: Bundle Secure
        run: bundle secure

  coditsu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Coditsu
        env:
          CODITSU_API_KEY: ${{ secrets.CODITSU_API_KEY }}
          CODITSU_API_SECRET: ${{ secrets.CODITSU_API_SECRET }}
        run: \curl -sSL https://api.coditsu.io/run/ci | bash
